package com.model;
// Generated 23/06/2017 05:20:26 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detailfile generated by hbm2java
 */
@Entity
@Table(name = "detailfile")
public class Detailfile implements java.io.Serializable {

	private int id;
	private State state;
	private String code;
	private String proposal;
	private String title;
	private String description;
	private Integer businesssubjectleaderid;
	private Integer businesssubjectcontrolid;
	private String state_1;
	private Date startdate;
	private Date enddate;
	private Date createdate;
	private Integer projectid;
	private Date updateat;
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<Project> projects_1 = new HashSet<Project>(0);

	public Detailfile() {
	}

	public Detailfile(int id) {
		this.id = id;
	}

	public Detailfile(int id, State state, String code, String proposal, String title, String description,
			Integer businesssubjectleaderid, Integer businesssubjectcontrolid, String state_1, Date startdate,
			Date enddate, Date createdate, Integer projectid, Date updateat, Set<Project> projects,
			Set<Project> projects_1) {
		this.id = id;
		this.state = state;
		this.code = code;
		this.proposal = proposal;
		this.title = title;
		this.description = description;
		this.businesssubjectleaderid = businesssubjectleaderid;
		this.businesssubjectcontrolid = businesssubjectcontrolid;
		this.state_1 = state_1;
		this.startdate = startdate;
		this.enddate = enddate;
		this.createdate = createdate;
		this.projectid = projectid;
		this.updateat = updateat;
		this.projects = projects;
		this.projects_1 = projects_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateid")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "code", length = 250)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "proposal", length = 250)
	public String getProposal() {
		return this.proposal;
	}

	public void setProposal(String proposal) {
		this.proposal = proposal;
	}

	@Column(name = "title", length = 250)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "businesssubjectleaderid")
	public Integer getBusinesssubjectleaderid() {
		return this.businesssubjectleaderid;
	}

	public void setBusinesssubjectleaderid(Integer businesssubjectleaderid) {
		this.businesssubjectleaderid = businesssubjectleaderid;
	}

	@Column(name = "businesssubjectcontrolid")
	public Integer getBusinesssubjectcontrolid() {
		return this.businesssubjectcontrolid;
	}

	public void setBusinesssubjectcontrolid(Integer businesssubjectcontrolid) {
		this.businesssubjectcontrolid = businesssubjectcontrolid;
	}

	@Column(name = "state", length = 250)
	public String getState_1() {
		return this.state_1;
	}

	public void setState_1(String state_1) {
		this.state_1 = state_1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startdate", length = 13)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enddate", length = 13)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdate", length = 13)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "projectid")
	public Integer getProjectid() {
		return this.projectid;
	}

	public void setProjectid(Integer projectid) {
		this.projectid = projectid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updateat", length = 13)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detailfile")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detailfile")
	public Set<Project> getProjects_1() {
		return this.projects_1;
	}

	public void setProjects_1(Set<Project> projects_1) {
		this.projects_1 = projects_1;
	}

}
