package com.model;
// Generated 21/05/2017 02:53:53 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name = "document")
public class Document implements java.io.Serializable {

	private int id;
	private Processgrouptype processgrouptype;
	private Documenttype documenttype;
	private State state;
	private String name;
	private String description;
	private String source;
	private String shortname;
	private Integer updateat;
	private Date createdate;

	public Document() {
	}

	public Document(int id) {
		this.id = id;
	}

	public Document(int id, Processgrouptype processgrouptype, Documenttype documenttype, State state, String name,
			String description, String source, String shortname, Integer updateat, Date createdate) {
		this.id = id;
		this.processgrouptype = processgrouptype;
		this.documenttype = documenttype;
		this.state = state;
		this.name = name;
		this.description = description;
		this.source = source;
		this.shortname = shortname;
		this.updateat = updateat;
		this.createdate = createdate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupprocesstypeid")
	public Processgrouptype getProcessgrouptype() {
		return this.processgrouptype;
	}

	public void setProcessgrouptype(Processgrouptype processgrouptype) {
		this.processgrouptype = processgrouptype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "documenttypeid")
	public Documenttype getDocumenttype() {
		return this.documenttype;
	}

	public void setDocumenttype(Documenttype documenttype) {
		this.documenttype = documenttype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateid")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "source", length = 250)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "shortname", length = 250)
	public String getShortname() {
		return this.shortname;
	}

	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	@Column(name = "updateat")
	public Integer getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Integer updateat) {
		this.updateat = updateat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdate", length = 13)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

}
