package com.model;
// Generated 23/06/2017 05:20:26 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Groupteam generated by hbm2java
 */
@Entity
@Table(name = "groupteam")
public class Groupteam implements java.io.Serializable {

	private int id;
	private Businessubject businessubject;
	private State state;
	private Team team;
	private Date createdate;
	private String description;
	private Double cost1;
	private Double cost2;

	public Groupteam() {
	}

	public Groupteam(int id) {
		this.id = id;
	}

	public Groupteam(int id, Businessubject businessubject, State state, Team team, Date createdate, String description,
			Double cost1, Double cost2) {
		this.id = id;
		this.businessubject = businessubject;
		this.state = state;
		this.team = team;
		this.createdate = createdate;
		this.description = description;
		this.cost1 = cost1;
		this.cost2 = cost2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "businessubjectid")
	public Businessubject getBusinessubject() {
		return this.businessubject;
	}

	public void setBusinessubject(Businessubject businessubject) {
		this.businessubject = businessubject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateid")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teamid")
	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdate", length = 13)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "cost1", precision = 17, scale = 17)
	public Double getCost1() {
		return this.cost1;
	}

	public void setCost1(Double cost1) {
		this.cost1 = cost1;
	}

	@Column(name = "cost2", precision = 17, scale = 17)
	public Double getCost2() {
		return this.cost2;
	}

	public void setCost2(Double cost2) {
		this.cost2 = cost2;
	}

}
