package com.model;
// Generated 21/05/2017 02:53:53 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Processgrouptype generated by hbm2java
 */
@Entity
@Table(name = "processgrouptype")
public class Processgrouptype implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private String shortname;
	private Set<Document> documents = new HashSet<Document>(0);

	public Processgrouptype() {
	}

	public Processgrouptype(int id) {
		this.id = id;
	}

	public Processgrouptype(int id, String name, String description, String shortname, Set<Document> documents) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.shortname = shortname;
		this.documents = documents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "shortname", length = 250)
	public String getShortname() {
		return this.shortname;
	}

	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processgrouptype")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

}
