package com.model;
// Generated 21/05/2017 02:53:53 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile")
public class Profile implements java.io.Serializable {

	private int id;
	private State state;
	private String name;
	private String description;
	private String createdate;
	private String updateat;
	private String code;
	private Set<Permissionprofile> permissionprofiles = new HashSet<Permissionprofile>(0);
	private Set<Userprofile> userprofiles = new HashSet<Userprofile>(0);

	public Profile() {
	}

	public Profile(int id) {
		this.id = id;
	}

	public Profile(int id, State state, String name, String description, String createdate, String updateat,
			String code, Set<Permissionprofile> permissionprofiles, Set<Userprofile> userprofiles) {
		this.id = id;
		this.state = state;
		this.name = name;
		this.description = description;
		this.createdate = createdate;
		this.updateat = updateat;
		this.code = code;
		this.permissionprofiles = permissionprofiles;
		this.userprofiles = userprofiles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateid")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "createdate", length = 250)
	public String getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(String createdate) {
		this.createdate = createdate;
	}

	@Column(name = "updateat", length = 250)
	public String getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(String updateat) {
		this.updateat = updateat;
	}

	@Column(name = "code", length = 250)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public Set<Permissionprofile> getPermissionprofiles() {
		return this.permissionprofiles;
	}

	public void setPermissionprofiles(Set<Permissionprofile> permissionprofiles) {
		this.permissionprofiles = permissionprofiles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public Set<Userprofile> getUserprofiles() {
		return this.userprofiles;
	}

	public void setUserprofiles(Set<Userprofile> userprofiles) {
		this.userprofiles = userprofiles;
	}

}
