package com.model;
// Generated 21/06/2017 07:36:26 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stakeholder generated by hbm2java
 */
@Entity
@Table(name = "stakeholder")
public class Stakeholder implements java.io.Serializable {

	private int id;
	private Businessubject businessubject;
	private State state;
	private String position;
	private String role;
	private String expectation;
	private String influence;
	private String interest;
	private Date createadate;
	private Date update;
	private Integer priorirty;

	public Stakeholder() {
	}

	public Stakeholder(int id) {
		this.id = id;
	}

	public Stakeholder(int id, Businessubject businessubject, State state, String position, String role,
			String expectation, String influence, String interest, Date createadate, Date update, Integer priorirty) {
		this.id = id;
		this.businessubject = businessubject;
		this.state = state;
		this.position = position;
		this.role = role;
		this.expectation = expectation;
		this.influence = influence;
		this.interest = interest;
		this.createadate = createadate;
		this.update = update;
		this.priorirty = priorirty;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "businesssubjectid")
	public Businessubject getBusinessubject() {
		return this.businessubject;
	}

	public void setBusinessubject(Businessubject businessubject) {
		this.businessubject = businessubject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateid")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "position", length = 250)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "role", length = 250)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "expectation", length = 250)
	public String getExpectation() {
		return this.expectation;
	}

	public void setExpectation(String expectation) {
		this.expectation = expectation;
	}

	@Column(name = "influence", length = 250)
	public String getInfluence() {
		return this.influence;
	}

	public void setInfluence(String influence) {
		this.influence = influence;
	}

	@Column(name = "interest", length = 250)
	public String getInterest() {
		return this.interest;
	}

	public void setInterest(String interest) {
		this.interest = interest;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createadate", length = 13)
	public Date getCreateadate() {
		return this.createadate;
	}

	public void setCreateadate(Date createadate) {
		this.createadate = createadate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "update", length = 13)
	public Date getUpdate() {
		return this.update;
	}

	public void setUpdate(Date update) {
		this.update = update;
	}

	@Column(name = "priorirty")
	public Integer getPriorirty() {
		return this.priorirty;
	}

	public void setPriorirty(Integer priorirty) {
		this.priorirty = priorirty;
	}

}
