package com.model;
// Generated 21/06/2017 07:36:26 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Taskhistory generated by hbm2java
 */
@Entity
@Table(name = "taskhistory")
public class Taskhistory implements java.io.Serializable {

	private int id;
	private Task task;
	private State state;
	private String comment;
	private Date createdate;
	private Integer businesssubjectmodifierid;
	private Date startdateAfter;
	private Date enddateAfter;
	private Date startdateUpdate;
	private Date enddateUpdate;
	private Double estimatehourAfter;
	private Double estimatehourNow;

	public Taskhistory() {
	}

	public Taskhistory(int id) {
		this.id = id;
	}

	public Taskhistory(int id, Task task, State state, String comment, Date createdate,
			Integer businesssubjectmodifierid, Date startdateAfter, Date enddateAfter, Date startdateUpdate,
			Date enddateUpdate, Double estimatehourAfter, Double estimatehourNow) {
		this.id = id;
		this.task = task;
		this.state = state;
		this.comment = comment;
		this.createdate = createdate;
		this.businesssubjectmodifierid = businesssubjectmodifierid;
		this.startdateAfter = startdateAfter;
		this.enddateAfter = enddateAfter;
		this.startdateUpdate = startdateUpdate;
		this.enddateUpdate = enddateUpdate;
		this.estimatehourAfter = estimatehourAfter;
		this.estimatehourNow = estimatehourNow;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taskid")
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateid")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "comment", length = 250)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdate", length = 13)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "businesssubjectmodifierid")
	public Integer getBusinesssubjectmodifierid() {
		return this.businesssubjectmodifierid;
	}

	public void setBusinesssubjectmodifierid(Integer businesssubjectmodifierid) {
		this.businesssubjectmodifierid = businesssubjectmodifierid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startdate_after", length = 13)
	public Date getStartdateAfter() {
		return this.startdateAfter;
	}

	public void setStartdateAfter(Date startdateAfter) {
		this.startdateAfter = startdateAfter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enddate_after", length = 13)
	public Date getEnddateAfter() {
		return this.enddateAfter;
	}

	public void setEnddateAfter(Date enddateAfter) {
		this.enddateAfter = enddateAfter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startdate_update", length = 13)
	public Date getStartdateUpdate() {
		return this.startdateUpdate;
	}

	public void setStartdateUpdate(Date startdateUpdate) {
		this.startdateUpdate = startdateUpdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "enddate_update", length = 13)
	public Date getEnddateUpdate() {
		return this.enddateUpdate;
	}

	public void setEnddateUpdate(Date enddateUpdate) {
		this.enddateUpdate = enddateUpdate;
	}

	@Column(name = "estimatehour_after", precision = 17, scale = 17)
	public Double getEstimatehourAfter() {
		return this.estimatehourAfter;
	}

	public void setEstimatehourAfter(Double estimatehourAfter) {
		this.estimatehourAfter = estimatehourAfter;
	}

	@Column(name = "estimatehour_now", precision = 17, scale = 17)
	public Double getEstimatehourNow() {
		return this.estimatehourNow;
	}

	public void setEstimatehourNow(Double estimatehourNow) {
		this.estimatehourNow = estimatehourNow;
	}

}
