package com.model;
// Generated 29/06/2017 05:54:28 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Team generated by hbm2java
 */
@Entity
@Table(name = "team")
public class Team implements java.io.Serializable {

	private int id;
	private Businessubject businessubject;
	private Project project;
	private State state;
	private String name;
	private String description;
	private Date updateat;
	private Date createdate;
	private Set<Groupteam> groupteams = new HashSet<Groupteam>(0);

	public Team() {
	}

	public Team(int id, Date updateat) {
		this.id = id;
		this.updateat = updateat;
	}

	public Team(int id, Businessubject businessubject, Project project, State state, String name, String description,
			Date updateat, Date createdate, Set<Groupteam> groupteams) {
		this.id = id;
		this.businessubject = businessubject;
		this.project = project;
		this.state = state;
		this.name = name;
		this.description = description;
		this.updateat = updateat;
		this.createdate = createdate;
		this.groupteams = groupteams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "businesssubjectid")
	public Businessubject getBusinessubject() {
		return this.businessubject;
	}

	public void setBusinessubject(Businessubject businessubject) {
		this.businessubject = businessubject;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "projectid")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateid")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updateat", nullable = false, length = 13)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdate", length = 13)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "team")
	public Set<Groupteam> getGroupteams() {
		return this.groupteams;
	}

	public void setGroupteams(Set<Groupteam> groupteams) {
		this.groupteams = groupteams;
	}

}
