package com.model;
// Generated 21/06/2017 07:36:26 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Team generated by hbm2java
 */
@Entity
@Table(name = "team")
public class Team implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private Integer businesssubjectid;
	private Date updateat;
	private Integer stateid;
	private Date createdate;
	private Set<Groupteam> groupteams = new HashSet<Groupteam>(0);

	public Team() {
	}

	public Team(int id) {
		this.id = id;
	}

	public Team(int id, String name, String description, Integer businesssubjectid, Date updateat, Integer stateid,
			Date createdate, Set<Groupteam> groupteams) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.businesssubjectid = businesssubjectid;
		this.updateat = updateat;
		this.stateid = stateid;
		this.createdate = createdate;
		this.groupteams = groupteams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 250)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "businesssubjectid")
	public Integer getBusinesssubjectid() {
		return this.businesssubjectid;
	}

	public void setBusinesssubjectid(Integer businesssubjectid) {
		this.businesssubjectid = businesssubjectid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updateat", length = 13)
	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	@Column(name = "stateid")
	public Integer getStateid() {
		return this.stateid;
	}

	public void setStateid(Integer stateid) {
		this.stateid = stateid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "createdate", length = 13)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "team")
	public Set<Groupteam> getGroupteams() {
		return this.groupteams;
	}

	public void setGroupteams(Set<Groupteam> groupteams) {
		this.groupteams = groupteams;
	}

}
